import {
  ComplianceObligation,
  Regulation,
  ComplianceAssessment,
  ComplianceActionPlan,
  ComplianceKPIs,
  ObligationsByStatus,
  ObligationsByFrequency,
  ComplianceTrend,
  ObligationsByRegulation,
  ComplianceHeatmapData,
} from '@/types/compliance'

// Mock Compliance Obligations
export const mockObligations: ComplianceObligation[] = [
  {
    id: 1,
    obligationCode: 'OBL-GDPR-001',
    title: 'Data Subject Access Request Response',
    regulation: 'GDPR',
    regulationId: 1,
    regulationCategory: 'Data Privacy',
    description: 'Respond to data subject access requests within 30 days',
    frequency: 'event_driven',
    status: 'compliant',
    owner: 'Sarah Johnson',
    ownerId: 102,
    department: 'Legal',
    departmentId: 4,
    dueDate: '2024-12-31',
    lastAssessmentDate: '2024-10-01',
    nextAssessmentDate: '2025-01-01',
    complianceScore: 95,
    priority: 'high',
    evidenceRequired: ['Response logs', 'Process documentation', 'Training records'],
    evidenceAttached: ['dsar_response_log_Q3.xlsx'],
    jurisdiction: 'European Union',
    effectiveDate: '2024-01-01',
    createdAt: '2023-12-01T10:00:00Z',
    updatedAt: '2024-10-01T14:30:00Z',
  },
  {
    id: 2,
    obligationCode: 'OBL-SOX-001',
    title: 'Annual Financial Audit',
    regulation: 'Sarbanes-Oxley Act',
    regulationId: 2,
    regulationCategory: 'Financial',
    description: 'Conduct annual independent financial audit',
    frequency: 'annually',
    status: 'compliant',
    owner: 'David Lee',
    ownerId: 103,
    department: 'Finance',
    departmentId: 3,
    dueDate: '2025-03-31',
    lastAssessmentDate: '2024-03-31',
    nextAssessmentDate: '2025-03-31',
    complianceScore: 98,
    priority: 'critical',
    evidenceRequired: ['Audit report', 'Management letter', 'Corrective action plans'],
    evidenceAttached: ['annual_audit_2024.pdf'],
    jurisdiction: 'United States',
    effectiveDate: '2023-01-01',
    createdAt: '2023-01-15T09:00:00Z',
    updatedAt: '2024-04-15T16:20:00Z',
  },
  {
    id: 3,
    obligationCode: 'OBL-POPIA-001',
    title: 'Privacy Impact Assessment',
    regulation: 'POPIA',
    regulationId: 3,
    regulationCategory: 'Data Privacy',
    description: 'Conduct privacy impact assessments for high-risk processing',
    frequency: 'quarterly',
    status: 'non_compliant',
    owner: 'Lisa Anderson',
    ownerId: 104,
    department: 'IT',
    departmentId: 1,
    dueDate: '2024-10-31',
    lastAssessmentDate: '2024-07-15',
    nextAssessmentDate: '2024-10-31',
    complianceScore: 45,
    priority: 'high',
    evidenceRequired: ['PIA reports', 'Risk assessments', 'Mitigation plans'],
    evidenceAttached: [],
    jurisdiction: 'South Africa',
    effectiveDate: '2024-01-01',
    createdAt: '2023-11-01T11:30:00Z',
    updatedAt: '2024-10-10T09:45:00Z',
  },
  {
    id: 4,
    obligationCode: 'OBL-ISO-001',
    title: 'Information Security Management System Review',
    regulation: 'ISO 27001',
    regulationId: 4,
    regulationCategory: 'Security',
    description: 'Annual review of ISMS policies and procedures',
    frequency: 'annually',
    status: 'compliant',
    owner: 'John Smith',
    ownerId: 101,
    department: 'IT',
    departmentId: 1,
    dueDate: '2025-06-30',
    lastAssessmentDate: '2024-06-30',
    nextAssessmentDate: '2025-06-30',
    complianceScore: 92,
    priority: 'medium',
    evidenceRequired: ['ISMS documentation', 'Review minutes', 'Action plans'],
    evidenceAttached: ['isms_review_2024.pdf'],
    jurisdiction: 'International',
    effectiveDate: '2023-07-01',
    createdAt: '2023-06-01T10:15:00Z',
    updatedAt: '2024-07-05T13:40:00Z',
  },
  {
    id: 5,
    obligationCode: 'OBL-OSHA-001',
    title: 'Workplace Safety Inspection',
    regulation: 'OSHA Standards',
    regulationId: 5,
    regulationCategory: 'Health & Safety',
    description: 'Monthly workplace safety inspections and reporting',
    frequency: 'monthly',
    status: 'partially_compliant',
    owner: 'Kevin Martinez',
    ownerId: 105,
    department: 'Operations',
    departmentId: 5,
    dueDate: '2024-10-31',
    lastAssessmentDate: '2024-09-30',
    nextAssessmentDate: '2024-10-31',
    complianceScore: 72,
    priority: 'high',
    evidenceRequired: ['Inspection reports', 'Hazard logs', 'Corrective actions'],
    evidenceAttached: ['safety_inspection_sep_2024.pdf'],
    jurisdiction: 'United States',
    effectiveDate: '2024-01-01',
    createdAt: '2023-12-15T08:30:00Z',
    updatedAt: '2024-10-01T11:20:00Z',
  },
  {
    id: 6,
    obligationCode: 'OBL-PCI-001',
    title: 'PCI DSS Compliance Assessment',
    regulation: 'PCI DSS',
    regulationId: 6,
    regulationCategory: 'Security',
    description: 'Quarterly PCI DSS self-assessment questionnaire',
    frequency: 'quarterly',
    status: 'under_review',
    owner: 'Thomas Jackson',
    ownerId: 107,
    department: 'IT',
    departmentId: 1,
    dueDate: '2024-12-31',
    lastAssessmentDate: '2024-09-30',
    nextAssessmentDate: '2024-12-31',
    complianceScore: 88,
    priority: 'critical',
    evidenceRequired: ['SAQ documentation', 'Scan reports', 'Attestation of compliance'],
    evidenceAttached: ['pci_saq_q3_2024.pdf'],
    jurisdiction: 'Global',
    effectiveDate: '2024-01-01',
    createdAt: '2023-11-20T09:00:00Z',
    updatedAt: '2024-10-05T15:10:00Z',
  },
  {
    id: 7,
    obligationCode: 'OBL-AML-001',
    title: 'Anti-Money Laundering Training',
    regulation: 'Anti-Money Laundering Act',
    regulationId: 7,
    regulationCategory: 'Anti-Corruption',
    description: 'Annual AML training for all relevant staff',
    frequency: 'annually',
    status: 'compliant',
    owner: 'Daniel Martinez',
    ownerId: 108,
    department: 'Compliance',
    departmentId: 7,
    dueDate: '2025-02-28',
    lastAssessmentDate: '2024-02-28',
    nextAssessmentDate: '2025-02-28',
    complianceScore: 100,
    priority: 'high',
    evidenceRequired: ['Training records', 'Completion certificates', 'Test results'],
    evidenceAttached: ['aml_training_2024.xlsx'],
    jurisdiction: 'United States',
    effectiveDate: '2023-03-01',
    createdAt: '2023-02-01T10:00:00Z',
    updatedAt: '2024-03-10T14:25:00Z',
  },
  {
    id: 8,
    obligationCode: 'OBL-ENV-001',
    title: 'Environmental Impact Reporting',
    regulation: 'Environmental Protection Act',
    regulationId: 8,
    regulationCategory: 'Environmental',
    description: 'Semi-annual environmental impact reporting',
    frequency: 'semi_annually',
    status: 'non_compliant',
    owner: 'Patricia Wilson',
    ownerId: 106,
    department: 'Operations',
    departmentId: 5,
    dueDate: '2024-10-30',
    lastAssessmentDate: '2024-04-30',
    nextAssessmentDate: '2024-10-30',
    complianceScore: 38,
    priority: 'medium',
    evidenceRequired: ['Impact assessments', 'Emissions data', 'Mitigation reports'],
    evidenceAttached: [],
    jurisdiction: 'United Kingdom',
    effectiveDate: '2024-01-01',
    createdAt: '2023-12-10T11:00:00Z',
    updatedAt: '2024-10-15T16:30:00Z',
  },
]

// Mock Regulations
export const mockRegulations: Regulation[] = [
  {
    id: 1,
    name: 'General Data Protection Regulation',
    code: 'GDPR',
    category: 'Data Privacy',
    jurisdiction: 'European Union',
    description: 'EU regulation on data protection and privacy',
    authority: 'European Commission',
    effectiveDate: '2018-05-25',
    lastUpdated: '2023-06-15',
    applicability: 'All organizations processing EU citizen data',
    obligationCount: 45,
    complianceRate: 87,
    status: 'active',
    relatedRegulations: [3],
    createdAt: '2023-01-10T10:00:00Z',
    updatedAt: '2024-09-20T14:30:00Z',
  },
  {
    id: 2,
    name: 'Sarbanes-Oxley Act',
    code: 'SOX',
    category: 'Financial',
    jurisdiction: 'United States',
    description: 'Federal law for financial reporting and corporate governance',
    authority: 'US Congress',
    effectiveDate: '2002-07-30',
    lastUpdated: '2023-01-15',
    applicability: 'Public companies',
    obligationCount: 38,
    complianceRate: 95,
    status: 'active',
    relatedRegulations: [],
    createdAt: '2023-01-15T09:00:00Z',
    updatedAt: '2024-08-10T11:20:00Z',
  },
  {
    id: 3,
    name: 'Protection of Personal Information Act',
    code: 'POPIA',
    category: 'Data Privacy',
    jurisdiction: 'South Africa',
    description: 'South African data protection legislation',
    authority: 'Information Regulator',
    effectiveDate: '2021-07-01',
    lastUpdated: '2023-09-10',
    applicability: 'All organizations processing personal information',
    obligationCount: 52,
    complianceRate: 72,
    status: 'active',
    relatedRegulations: [1],
    createdAt: '2023-02-01T10:30:00Z',
    updatedAt: '2024-09-15T13:45:00Z',
  },
  {
    id: 4,
    name: 'ISO 27001',
    code: 'ISO-27001',
    category: 'Security',
    jurisdiction: 'International',
    description: 'International standard for information security management',
    authority: 'ISO/IEC',
    effectiveDate: '2013-10-01',
    lastUpdated: '2022-10-25',
    applicability: 'Organizations seeking ISMS certification',
    obligationCount: 35,
    complianceRate: 92,
    status: 'active',
    relatedRegulations: [],
    createdAt: '2023-03-01T11:00:00Z',
    updatedAt: '2024-07-20T15:10:00Z',
  },
  {
    id: 5,
    name: 'Occupational Safety and Health Act',
    code: 'OSHA',
    category: 'Health & Safety',
    jurisdiction: 'United States',
    description: 'Federal law governing workplace safety and health',
    authority: 'Department of Labor',
    effectiveDate: '1970-12-29',
    lastUpdated: '2024-03-15',
    applicability: 'All employers and employees',
    obligationCount: 67,
    complianceRate: 78,
    status: 'active',
    relatedRegulations: [],
    createdAt: '2023-01-20T09:15:00Z',
    updatedAt: '2024-09-05T12:30:00Z',
  },
  {
    id: 6,
    name: 'Payment Card Industry Data Security Standard',
    code: 'PCI-DSS',
    category: 'Security',
    jurisdiction: 'Global',
    description: 'Security standard for organizations handling credit card data',
    authority: 'PCI Security Standards Council',
    effectiveDate: '2004-12-15',
    lastUpdated: '2024-03-31',
    applicability: 'Organizations processing, storing, or transmitting card data',
    obligationCount: 42,
    complianceRate: 88,
    status: 'active',
    relatedRegulations: [],
    createdAt: '2023-02-10T10:45:00Z',
    updatedAt: '2024-08-25T14:20:00Z',
  },
]

// Mock Compliance KPIs
export const mockComplianceKPIs: ComplianceKPIs = {
  totalObligations: 124,
  complianceRate: 83.5,
  overdueObligations: 8,
  upcomingDeadlines: 12,
  activeRegulations: 15,
  openNonConformances: 5,
  monthlyChanges: {
    total: 3.2,
    compliant: 4.5,
    overdue: -15.2,
    assessments: 8.7,
  },
}

// Mock Obligations by Status
export const mockObligationsByStatus: ObligationsByStatus[] = [
  { name: 'Compliant', value: 68, color: '#10B981' },
  { name: 'Non-Compliant', value: 12, color: '#EF4444' },
  { name: 'Partially Compliant', value: 18, color: '#F59E0B' },
  { name: 'Under Review', value: 26, color: '#3B82F6' },
]

// Mock Obligations by Frequency
export const mockObligationsByFrequency: ObligationsByFrequency[] = [
  { name: 'Daily', value: 8 },
  { name: 'Weekly', value: 12 },
  { name: 'Monthly', value: 35 },
  { name: 'Quarterly', value: 28 },
  { name: 'Annually', value: 41 },
]

// Mock Compliance Trend (last 12 months)
export const mockComplianceTrend: ComplianceTrend[] = [
  { period: 'Nov 23', compliant: 58, nonCompliant: 18, partiallyCompliant: 15, rate: 75 },
  { period: 'Dec 23', compliant: 60, nonCompliant: 17, partiallyCompliant: 14, rate: 77 },
  { period: 'Jan 24', compliant: 62, nonCompliant: 16, partiallyCompliant: 13, rate: 79 },
  { period: 'Feb 24', compliant: 63, nonCompliant: 15, partiallyCompliant: 14, rate: 79.5 },
  { period: 'Mar 24', compliant: 64, nonCompliant: 15, partiallyCompliant: 13, rate: 80 },
  { period: 'Apr 24', compliant: 65, nonCompliant: 14, partiallyCompliant: 14, rate: 80.5 },
  { period: 'May 24', compliant: 66, nonCompliant: 14, partiallyCompliant: 13, rate: 81 },
  { period: 'Jun 24', compliant: 67, nonCompliant: 13, partiallyCompliant: 14, rate: 81.5 },
  { period: 'Jul 24', compliant: 67, nonCompliant: 13, partiallyCompliant: 15, rate: 81 },
  { period: 'Aug 24', compliant: 68, nonCompliant: 12, partiallyCompliant: 16, rate: 82 },
  { period: 'Sep 24', compliant: 68, nonCompliant: 12, partiallyCompliant: 18, rate: 82.5 },
  { period: 'Oct 24', compliant: 68, nonCompliant: 12, partiallyCompliant: 18, rate: 83.5 },
]

// Mock Obligations by Regulation
export const mockObligationsByRegulation: ObligationsByRegulation[] = [
  { name: 'GDPR', total: 45, compliant: 38, nonCompliant: 3, partiallyCompliant: 4, complianceRate: 84 },
  { name: 'SOX', total: 38, compliant: 36, nonCompliant: 1, partiallyCompliant: 1, complianceRate: 95 },
  { name: 'POPIA', total: 52, compliant: 35, nonCompliant: 8, partiallyCompliant: 9, complianceRate: 67 },
  { name: 'ISO 27001', total: 35, compliant: 32, nonCompliant: 1, partiallyCompliant: 2, complianceRate: 91 },
  { name: 'OSHA', total: 67, compliant: 50, nonCompliant: 7, partiallyCompliant: 10, complianceRate: 75 },
  { name: 'PCI DSS', total: 42, compliant: 37, nonCompliant: 2, partiallyCompliant: 3, complianceRate: 88 },
]

// Mock Compliance Heatmap Data
export const mockComplianceHeatmap: ComplianceHeatmapData[] = [
  {
    department: 'IT',
    regulations: {
      'GDPR': 'compliant',
      'ISO 27001': 'compliant',
      'PCI DSS': 'partially_compliant',
      'POPIA': 'compliant',
    },
  },
  {
    department: 'Finance',
    regulations: {
      'SOX': 'compliant',
      'GDPR': 'compliant',
      'Anti-Money Laundering': 'compliant',
      'Tax Regulations': 'compliant',
    },
  },
  {
    department: 'HR',
    regulations: {
      'GDPR': 'partially_compliant',
      'POPIA': 'non_compliant',
      'Employment Law': 'compliant',
      'Health & Safety': 'compliant',
    },
  },
  {
    department: 'Operations',
    regulations: {
      'OSHA': 'partially_compliant',
      'Environmental': 'non_compliant',
      'Quality Standards': 'compliant',
      'Health & Safety': 'partially_compliant',
    },
  },
  {
    department: 'Legal',
    regulations: {
      'GDPR': 'compliant',
      'POPIA': 'compliant',
      'Anti-Bribery': 'compliant',
      'Competition Law': 'compliant',
    },
  },
]

// Mock Critical Obligations
export const mockCriticalObligations: ComplianceObligation[] = mockObligations
  .filter((obl) => obl.priority === 'critical' || obl.priority === 'high')
  .slice(0, 5)

// Mock Recent Assessments (simplified for dashboard display)
export const mockRecentAssessments = [
  {
    id: 1,
    assessmentNumber: 'ASM-2024-001',
    title: 'Q3 GDPR Compliance Assessment',
    regulation: 'GDPR',
    assessmentDate: '2024-09-30',
    status: 'completed',
    overallScore: 87,
    complianceLevel: 'compliant' as const,
  },
  {
    id: 2,
    assessmentNumber: 'ASM-2024-002',
    title: 'SOX Annual Audit',
    regulation: 'SOX',
    assessmentDate: '2024-09-15',
    status: 'completed',
    overallScore: 95,
    complianceLevel: 'compliant' as const,
  },
  {
    id: 3,
    assessmentNumber: 'ASM-2024-003',
    title: 'POPIA Gap Analysis',
    regulation: 'POPIA',
    assessmentDate: '2024-10-05',
    status: 'completed',
    overallScore: 68,
    complianceLevel: 'partially_compliant' as const,
  },
  {
    id: 4,
    assessmentNumber: 'ASM-2024-004',
    title: 'ISO 27001 Surveillance Audit',
    regulation: 'ISO 27001',
    assessmentDate: '2024-10-10',
    status: 'in_progress',
    overallScore: 0,
    complianceLevel: 'under_review' as const,
  },
  {
    id: 5,
    assessmentNumber: 'ASM-2024-005',
    title: 'Workplace Safety Inspection',
    regulation: 'OSHA',
    assessmentDate: '2024-10-08',
    status: 'completed',
    overallScore: 72,
    complianceLevel: 'partially_compliant' as const,
  },
]

